---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dannrero/public_html
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
